FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/tmp/uploads

ENV PYTHONUNBUFFERED=1

CMD gunicorn app:app -b 0.0.0.0:${PORT:8000}