from . import upload_asklaila_task
from . import upload_atm_task
from . import upload_bank_task
from . import upload_college_dunia_task
from . import upload_freelisting_task
from . import upload_google_map_scrape_task
from . import upload_google_map_task
from . import upload_heyplaces_task
from . import upload_justdial_task
from . import upload_magicpin_task
from . import upload_nearbuy_task
from . import upload_pinda_task
from . import upload_post_office_task
from . import upload_schoolgis_task
from . import upload_shiksha_task
from . import upload_yellow_pages_task